### ISSUE TITLE
Pick a unit test framework

### ISSUE THREAD

**Issue by AdamNorberg** [Freedom-of-Form-Foundation/anatomy3d#12]
This code has no tests. Step 1 in adding tests: pick a unit test framework.

**Comment by AdamNorberg** [comment]
Five seconds on Google: xUnit (https://github.com/xunit/xunit), NUnit (https://nunit.org/).

**Comment by AdamNorberg** [comment]
https://github.com/godotengine/godot-proposals/issues/432 - Godot is difficult to unit test. This issue is active as recently as a couple of weeks ago.

**Comment by AdamNorberg** [comment]
https://github.com/NathanWarden/godot-test-tools - for nUnit, folks are already working around this. This repository hasn't been updated for three years, but if it's close to working, maybe I can get it the rest of the way...

**Comment by AdamNorberg** [comment]
https://godotengine.org/qa/73382/setup-nunit-c%23-on-windows - information on getting nUnit running inside the context of Godot. We'll have some tests under Godot and some tests that work independently of it (engine-targeted), but it shouldn't be hard to set up the independent tests vs. the Godot-integrated tests, we can just do a "normal" engine setup as long as the engine code is avoiding taking dependencies on the UI and graphics code. (If it isn't, we might have some refactoring to do.)

**Comment by AdamNorberg** [comment]
Okay, after a bunch of research, I've found that the general C# community consensus is that while nUnit is more established, xUnit is better-designed. xUnit behaves more similarly to the tools I'm used to, certainly; they've chosen some vaguely silly attribute names (a test case is called a `[Fact]`, apparently) but that's forgiveable, if silly but unambiguous names are the worst problem I can find I have no qualms.

xUnit runs each test in a separate instance of the test class; nUnit reuses the test class. From personal experience, I strongly favor the xUnit approach here. That alone is enough to make me pick xUnit for a new project and, since this project has never had unit tests before, it's a new project as far as picking a test framework is concerned!

So: **I nominate xUnit.**

https://github.com/fledware/GodotXUnit  -- running it in Godot. (Godot asset library item: https://godotengine.org/asset-library/asset/688 )

https://xunit.net - web site
https://github.com/xunit/xunit  -- github project

Any other views on picking a test framework?

**Comment by Lathreas** [comment]
> [godotengine/godot-proposals#432](https://github.com/godotengine/godot-proposals/issues/432) - Godot is difficult to unit test. This issue is active as recently as a couple of weeks ago.

Oh, in relation to this, I should also note that although Godot integration is highly appreciated, a lot of the engine works quite distantly from Godot itself so it should be able to work without any calls to Godot. This means, in principle, that we can safely unit test the engine, although we might need to do some trouble for unit testing the UI frontend.

**Comment by GeorgeS2019** [comment]
@AdamNorberg @Lathreas 
[This is where we focus on C# unit test discussion](https://github.com/godotengine/godot-proposals/issues/432)
