### ISSUE TITLE
Implement raytracing of surfaces deformed by a ContinuousMap

### ISSUE THREAD

**Issue by Lathreas** [Freedom-of-Form-Foundation/anatomy3d#15]
For various features of the software, such as projecting a bone surface onto the surface of a joint object, we need some form of raytracing. Since all surfaces are defined as a smooth base geometry (which is implemented as a `Surface`) deformed by a heightmap (which is implemented as a `ContinuousMap`), we need to implement some form of raytracer that can query the distance between any point and an arbitrary surface.

**Comment by AdamNorberg** [comment]
Thought debris for the future: for now, `Surface` + `ContinuousMap` describes "a raytraceable thing", but if this starts to look more complicated than hoped, `IRaytraceable` might be useful to define as "something that can answer the questions a raytracer needs", with `MappedSurface` representing the specific Surface + ContinuousMap version.
