### ISSUE TITLE
Set up code documentation generator

### ISSUE THREAD

**Issue by Lathreas** [Freedom-of-Form-Foundation/anatomy3d#30]
It might be nice to add some automated code documentation generator, such as Doxygen, for future reference. This allows users of the engine (and ourselves) to easily browse the different classes and methods that exist and see their functionality.

**Comment by AdamNorberg** [comment]
371870

**Comment by AdamNorberg** [comment]
https://ntamonsec.blogspot.com/2020/06/github-actions-doxygen-documentation.html?m=1
